# Generated by Django 5.2 on 2025-05-07 23:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cultivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('thc_estimado', models.FloatField(blank=True, null=True, verbose_name='THC Estimado (%)')),
                ('cbd_estimado', models.FloatField(blank=True, null=True, verbose_name='CBD Estimado (%)')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='areacultivo',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Altura en metros', max_digits=5),
        ),
        migrations.AddField(
            model_name='areacultivo',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ancho en metros', max_digits=5),
        ),
        migrations.AddField(
            model_name='areacultivo',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='areacultivo',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Largo en metros', max_digits=5),
        ),
        migrations.AddField(
            model_name='planta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sala',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Altura en metros', max_digits=5),
        ),
        migrations.AddField(
            model_name='sala',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ancho en metros', max_digits=5),
        ),
        migrations.AddField(
            model_name='sala',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sala',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Largo en metros', max_digits=5),
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('vegetacion', 'Vegetación'), ('floracion', 'Floración'), ('mixta', 'Mixta'), ('ciclo_completo', 'Ciclo Completo'), ('otro', 'Otro')], default='mixta', max_length=20),
        ),
        migrations.AlterField(
            model_name='areacultivo',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cultivo.sala'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cultivo.areacultivo'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='cbd_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje estimado de CBD', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='etapa_actual',
            field=models.CharField(choices=[('germinacion', 'Germinación'), ('planta_bebe', 'Planta Bebé'), ('vegetacion', 'Vegetación'), ('pre_floracion', 'Pre-Floración'), ('floracion', 'Floración'), ('cosecha', 'Cosecha'), ('secado', 'Secado'), ('curado', 'Curado')], default='germinacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planta',
            name='thc_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje estimado de THC', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='genetica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cultivo.genetica'),
        ),
    ]
