# Generated by Django 5.2 on 2025-05-07 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cultivo', '0002_genetica_areacultivo_altura_areacultivo_ancho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacultivo',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='gestion_cultivo.sala'),
        ),
    ]
