# Generated by Django 5.2 on 2025-05-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cultivo', '0003_alter_areacultivo_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacultivo',
            name='cantidad_plantas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='areacultivo',
            name='sustrato',
            field=models.CharField(blank=True, choices=[('tierra', 'Tierra'), ('coco', 'Coco'), ('perlita', 'Perlita'), ('vermiculita', 'Vermiculita'), ('lana_roca', 'Lana de Roca'), ('arcilla', 'Arcilla Expandida'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='areacultivo',
            name='tamano_balde',
            field=models.CharField(blank=True, choices=[('5l', '5 Litros'), ('10l', '10 Litros'), ('15l', '15 Litros'), ('20l', '20 Litros'), ('otro', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='areacultivo',
            name='tamano_maceta',
            field=models.CharField(blank=True, choices=[('1l', '1 Litro'), ('3l', '3 Litros'), ('5l', '5 Litros'), ('7l', '7 Litros'), ('10l', '10 Litros'), ('15l', '15 Litros'), ('20l', '20 Litros'), ('otro', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='areacultivo',
            name='tipo_cultivo',
            field=models.CharField(choices=[('suelo', 'Suelo'), ('coco', 'Coco'), ('hidroponico', 'Hidropónico'), ('aeroponico', 'Aeropónico')], default='suelo', max_length=20),
        ),
    ]
