# Generated by Django 5.2 on 2025-05-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cultivo', '0004_areacultivo_cantidad_plantas_areacultivo_sustrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacultivo',
            name='cantidad_plantas',
        ),
        migrations.AddField(
            model_name='areacultivo',
            name='composicion_sustrato',
            field=models.TextField(blank=True, help_text='Describe la composición personalizada del sustrato', null=True),
        ),
        migrations.AddField(
            model_name='areacultivo',
            name='tiene_riego_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='areacultivo',
            name='sustrato',
            field=models.CharField(blank=True, choices=[('tierra_100', '100% Tierra'), ('coco_100', '100% Coco'), ('tierra_coco_50_50', '50% Tierra - 50% Coco'), ('tierra_hummus_50_50', '50% Tierra - 50% Hummus'), ('tierra_perlita_70_30', '70% Tierra - 30% Perlita'), ('coco_perlita_70_30', '70% Coco - 30% Perlita'), ('personalizado', 'Personalizado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='areacultivo',
            name='tipo_cultivo',
            field=models.CharField(choices=[('suelo', 'Suelo'), ('hidroponico', 'Hidropónico'), ('living_soil', 'Living Soil')], default='suelo', max_length=20),
        ),
    ]
