# Generated by Django 5.2 on 2025-05-08 00:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cultivo', '0005_remove_areacultivo_cantidad_plantas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='planta',
            name='genetica',
        ),
        migrations.AddField(
            model_name='planta',
            name='es_madre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planta',
            name='planta_madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esquejes', to='gestion_cultivo.planta'),
        ),
        migrations.AddField(
            model_name='planta',
            name='tipo_planta',
            field=models.CharField(choices=[('semilla', 'Semilla'), ('esqueje', 'Esqueje')], default='semilla', max_length=20),
        ),
        migrations.AddField(
            model_name='planta',
            name='semilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cultivo.semilla'),
        ),
    ]
