# Generated by Django 5.2 on 2025-05-08 02:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cultivo', '0006_semilla_remove_planta_genetica_planta_es_madre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='semilla',
            old_name='fecha_creacion',
            new_name='fecha_agregado',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='largo',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='cantidad_disponible',
        ),
        migrations.AddField(
            model_name='areacultivo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacultivo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En Mantenimiento')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='genetica',
            name='rendimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='genetica',
            name='tiempo_floracion',
            field=models.PositiveIntegerField(blank=True, help_text='Días de floración', null=True),
        ),
        migrations.AddField(
            model_name='genetica',
            name='tipo',
            field=models.CharField(choices=[('sativa', 'Sativa'), ('indica', 'Indica'), ('hibrida', 'Híbrida'), ('ruderalis', 'Ruderalis')], default='hibrida', max_length=20),
        ),
        migrations.AddField(
            model_name='sala',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='horas_luz',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='sala',
            name='humedad_objetivo',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='temperatura_objetivo',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo_iluminacion',
            field=models.CharField(choices=[('led', 'LED'), ('hps', 'HPS'), ('cmh', 'CMH'), ('otro', 'Otro')], default='led', max_length=20),
        ),
        migrations.AddField(
            model_name='semilla',
            name='altura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='ambiente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='banco',
            field=models.CharField(blank=True, choices=[('dutch_passion', 'Dutch Passion'), ('sweet_seeds', 'Sweet Seeds'), ('barneys_farm', "Barney's Farm"), ('royal_queen_seeds', 'Royal Queen Seeds'), ('sensi_seeds', 'Sensi Seeds'), ('greenhouse_seeds', 'Greenhouse Seeds'), ('dinafem', 'Dinafem'), ('otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='semilla',
            name='cbd',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='genetica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='rendimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='thc',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='tiempo_floracion',
            field=models.PositiveIntegerField(blank=True, help_text='Días de floración', null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='tipo',
            field=models.CharField(choices=[('feminizada', 'Feminizada'), ('regular', 'Regular'), ('automatica', 'Automática')], default='feminizada', max_length=20),
        ),
        migrations.AddField(
            model_name='semilla',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sala',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('iluminacion', 'Iluminación'), ('ventilacion', 'Ventilación'), ('riego', 'Riego'), ('medicion', 'Medición'), ('otro', 'Otro')], max_length=20)),
                ('fecha_compra', models.DateField()),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('garantia', models.DateField(blank=True, null=True)),
                ('especificaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('base', 'Base'), ('estimulador', 'Estimulador'), ('micro', 'Micro'), ('otro', 'Otro')], max_length=20)),
                ('npk', models.CharField(blank=True, max_length=20)),
                ('fecha_compra', models.DateField()),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volumen', models.CharField(max_length=50)),
                ('instrucciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sustrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('tierra', 'Tierra'), ('coco', 'Coco'), ('hidroponico', 'Hidropónico'), ('otro', 'Otro')], max_length=20)),
                ('ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('fecha_compra', models.DateField()),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volumen', models.CharField(max_length=50)),
                ('caracteristicas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
