# Generated by Django 5.2 on 2025-05-14 07:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cultivo', '0008_banco_caracteristica_terpeno_remove_sustrato_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionFertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='base',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='lampara',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='maceta',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='fertilizante',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='fertilizante',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='fertilizante',
            name='fecha_agregado',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='dias_flora',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='fecha_agregado',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='fecha_compra',
        ),
        migrations.AddField(
            model_name='fertilizante',
            name='etapa_uso',
            field=models.CharField(blank=True, choices=[('crecimiento', 'Crecimiento'), ('floracion', 'Floración'), ('universal', 'Universal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fertilizante',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fertilizante',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='fertilizante',
            name='instrucciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fertilizante',
            name='medio_compatible',
            field=models.CharField(blank=True, choices=[('tierra', 'Tierra'), ('coco', 'Coco'), ('hidro', 'Hidroponía')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fertilizante',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fertilizante',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='ciclo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='padres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='tamano_blister',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='npk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='tipo',
            field=models.CharField(blank=True, choices=[('base', 'Base'), ('aditivo', 'Aditivo'), ('estimulante', 'Estimulante'), ('corrector', 'Corrector'), ('micorrizas', 'Micorrizas'), ('enzimas', 'Enzimas'), ('fungicida', 'Fungicida'), ('biocontrol', 'Biocontrol')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='semilla',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='semilla',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='semilla',
            name='porcentaje_cbd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='semilla',
            name='porcentaje_thc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='terpenos',
        ),
        migrations.AlterField(
            model_name='semilla',
            name='tipo',
            field=models.CharField(blank=True, choices=[('fotoperiodica', 'Fotoperiódica'), ('autofloreciente', 'Autofloreciente'), ('regular', 'Regular')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('maceta', 'Maceta'), ('bandeja', 'Bandeja de esquejes'), ('aeroclonador', 'Aeroclonador'), ('balde', 'Balde hidroponía')], max_length=20, null=True)),
                ('capacidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('iluminacion', 'Iluminación'), ('ventilacion', 'Ventilación'), ('controlador', 'Controlador'), ('bomba', 'Bomba'), ('medidor', 'Medidor')], max_length=20, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('potencia', models.CharField(blank=True, max_length=50, null=True)),
                ('voltaje', models.CharField(blank=True, max_length=50, null=True)),
                ('compatibilidad', models.CharField(blank=True, max_length=200, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True)),
                ('accesorios', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fertilizante',
            name='presentaciones',
            field=models.ManyToManyField(blank=True, related_name='fertilizantes', to='gestion_cultivo.presentacionfertilizante'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('semilla', 'Semilla'), ('fertilizante', 'Fertilizante'), ('contenedor', 'Contenedor'), ('maquinaria', 'Maquinaria')], max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('contenedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_cultivo.contenedor')),
                ('fertilizante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_cultivo.fertilizante')),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_cultivo.maquinaria')),
                ('semilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_cultivo.semilla')),
            ],
        ),
        migrations.DeleteModel(
            name='Aditivo',
        ),
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.DeleteModel(
            name='Lampara',
        ),
        migrations.DeleteModel(
            name='Maceta',
        ),
        migrations.AddField(
            model_name='semilla',
            name='terpenos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
