# Generated by Django 5.2 on 2025-05-14 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cultivo', '0009_presentacionfertilizante_remove_base_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacultivo',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='areacultivo',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='areacultivo',
            name='composicion_sustrato',
        ),
        migrations.RemoveField(
            model_name='areacultivo',
            name='largo',
        ),
        migrations.RemoveField(
            model_name='areacultivo',
            name='sustrato',
        ),
        migrations.RemoveField(
            model_name='areacultivo',
            name='tamano_balde',
        ),
        migrations.RemoveField(
            model_name='areacultivo',
            name='tamano_maceta',
        ),
        migrations.RemoveField(
            model_name='contenedor',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='fertilizante',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='genetica',
            name='cbd_estimado',
        ),
        migrations.RemoveField(
            model_name='genetica',
            name='thc_estimado',
        ),
        migrations.RemoveField(
            model_name='maquinaria',
            name='accesorios',
        ),
        migrations.RemoveField(
            model_name='maquinaria',
            name='compatibilidad',
        ),
        migrations.RemoveField(
            model_name='maquinaria',
            name='dimensiones',
        ),
        migrations.RemoveField(
            model_name='maquinaria',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='maquinaria',
            name='voltaje',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='cbd_estimado',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='es_madre',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='fecha_germinacion',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='planta_madre',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='semilla',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='thc_estimado',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='horas_luz',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='padres',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='porcentaje_cbd',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='porcentaje_thc',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='tamano_blister',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fecha_ingreso',
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='caracteristicas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='dimensiones',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fertilizante',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='caracteristicas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='instrucciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='planta',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentacionfertilizante',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='presentacionfertilizante',
            name='fertilizante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_cultivo.fertilizante'),
        ),
        migrations.AddField(
            model_name='semilla',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, to='gestion_cultivo.caracteristica'),
        ),
        migrations.AddField(
            model_name='semilla',
            name='cbd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='semilla',
            name='rendimiento',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='semilla',
            name='thc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='tiempo_floracion',
            field=models.IntegerField(blank=True, default=0, help_text='Días', null=True),
        ),
        migrations.AddField(
            model_name='semilla',
            name='variedad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stock',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='proveedor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terpeno',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='areacultivo',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='areacultivo',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='areacultivo',
            name='tipo_cultivo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='banco',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='banco',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='capacidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='material',
            field=models.CharField(blank=True, choices=[('plastico', 'Plástico'), ('tela', 'Tela'), ('ceramica', 'Cerámica'), ('otro', 'Otro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='tipo',
            field=models.CharField(blank=True, choices=[('maceta', 'Maceta'), ('bolsa', 'Bolsa'), ('otro', 'Otro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='etapa_uso',
            field=models.CharField(blank=True, choices=[('crecimiento', 'Crecimiento'), ('floracion', 'Floración'), ('ambas', 'Ambas')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='instrucciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='medio_compatible',
            field=models.CharField(blank=True, choices=[('suelo', 'Suelo'), ('hidroponico', 'Hidropónico'), ('ambos', 'Ambos')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='npk',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='fertilizante',
            name='presentaciones',
        ),
        migrations.AlterField(
            model_name='fertilizante',
            name='tipo',
            field=models.CharField(blank=True, choices=[('base', 'Base'), ('estimulador', 'Estimulador'), ('microbios', 'Microbios'), ('otro', 'Otro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='genetica',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='genetica',
            name='rendimiento',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='genetica',
            name='tiempo_floracion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='genetica',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='potencia',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='tipo',
            field=models.CharField(blank=True, choices=[('iluminacion', 'Iluminación'), ('ventilacion', 'Ventilación'), ('riego', 'Riego'), ('control', 'Control'), ('otro', 'Otro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='planta',
            name='etapa_actual',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='planta',
            name='tipo_planta',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='presentacionfertilizante',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presentacionfertilizante',
            name='tamano',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sala',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sala',
            name='humedad_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sala',
            name='temperatura_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipo_iluminacion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sala',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='semilla',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cultivo.banco'),
        ),
        migrations.AlterField(
            model_name='semilla',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='semilla',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='semilla',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='semilla',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='terpenos',
        ),
        migrations.AlterField(
            model_name='semilla',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lote',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tipo_producto',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='terpeno',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fertilizante',
            name='presentaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='semilla',
            name='terpenos',
            field=models.ManyToManyField(blank=True, to='gestion_cultivo.terpeno'),
        ),
    ]
